#index:
#    path: /
#    controller: App\Controller\DefaultController::index


GetPublishingController:
    path:       /publishinghouse
    controller: App\Controller\PublishingController::publishing
    methods:    GET

GetStyleController:
    path:       /style
    controller: App\Controller\StyleController::show
    methods:    GET

PostAuthorController:
    path: /author/{id_book}
    controller: App\Controller\AuthorController::show
    requirements:
      _method: POST

PostBascetController:
    path: /basket/{id_bascet}
    controller: App\Controller\BascetController::show
    requirements:
      _method: POST

PostRegistrationController:
    path: /registration
    controller: App\Controller\RegistrationController::create
    requirements:
      _method: POST

PostStyleBookController:
    path: /stylebook/{id_genre}
    controller: App\Controller\StyleBookController::show
    requirements:
      _method: POST

PostPublishingBookController:
    path: /publishingbook/{id_publishing_house}
    controller: App\Controller\PublishingBookController::show
    requirements:
      _method: POST
